# Generated by Django 4.2.13 on 2025-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'), ('import', 'Import'), ('export', 'Export'), ('reset', 'Reset'), ('rfid_scan', 'RFID Scan'), ('comment', 'Comment')], max_length=10),
        ),
    ]
