# Generated by Django 4.2.13 on 2025-06-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_log_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='verified',
            new_name='verified1',
        ),
        migrations.AddField(
            model_name='person',
            name='read_flag_in',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='read_flag_out',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='read_light_in',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='read_light_out',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='verified2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='verified3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
