# Generated by Django 4.2.13 on 2025-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_verified_person_verified1_person_read_flag_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='verified_updated_at1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='verified_updated_at2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='verified_updated_at3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
