# Generated by Django 4.2.13 on 2025-06-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_person_verified_updated_at1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='read_flag_in',
            new_name='read_flag',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='read_light_in',
            new_name='read_light',
        ),
        migrations.RemoveField(
            model_name='person',
            name='read_flag_out',
        ),
        migrations.RemoveField(
            model_name='person',
            name='read_light_out',
        ),
    ]
