# Generated by Django 4.2.13 on 2025-06-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_read_flag_in_person_read_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rfid',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
