# Generated by Django 4.2.13 on 2025-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_person_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rfid',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
