# Generated by Django 4.2.20 on 2025-10-02 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_log_action_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน'),
        ),
        migrations.AddField(
            model_name='log',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname'),
        ),
    ]
