# Generated by Django 4.2.13 on 2025-10-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='read_flag',
        ),
        migrations.RemoveField(
            model_name='person',
            name='read_light',
        ),
    ]
