# Generated by Django 4.2.13 on 2025-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_person_read_flag_remove_person_read_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nisit',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
